First revision

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -1,61 +1,87 @@
-# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
-# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
-name: CMake on multiple platforms
+# .github/workflows/cmake-multi-platform.yml
+
+name: CMake Build on Linux (GCC & Clang)
 
 on:
   push:
-    branches: [ "master" ]
+    # Add 'development' to the list of branches for push events
+    branches: [ "master", "development" ]
   pull_request:
-    branches: [ "master" ]
+    # Add 'development' to the list of branches for pull_request events
+    branches: [ "master", "development" ]
 
 jobs:
   build:
     runs-on: ${{ matrix.os }}
 
     strategy:
-      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
       fail-fast: false
-
-      # Set up a matrix to run the following 2 configurations:
-      # 1. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
-      # 2. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
-      #
-      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
       matrix:
         os: [ubuntu-latest]
         build_type: [Release]
-        cpp_compiler: [g++, clang++]
+        compiler: [gcc, clang] # Use short names for easier reference
+
+        # Define compiler specifics per matrix entry
         include:
-          - os: ubuntu-latest
+          - compiler: gcc
+            c_compiler: gcc
             cpp_compiler: g++
-          - os: ubuntu-latest
+          - compiler: clang
+            c_compiler: clang
             cpp_compiler: clang++
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    # ---- Installation Step ----
+    - name: Install Dependencies
+      run: |
+        sudo apt-get update -y
+        sudo apt-get install -y --no-install-recommends \
+          build-essential \
+          cmake \
+          ninja-build \
+          libevdev-dev \
+          libxss-dev \
+          libdbus-1-dev \
+          libglib2.0-dev
+        echo "--- Verifying Compiler Setup ---"
+        echo "Selected C Compiler for CMake: ${{ matrix.c_compiler }}"
+        echo "Selected C++ Compiler for CMake: ${{ matrix.cpp_compiler }}"
+
+        echo "Checking if selected compilers exist in PATH:"
+        which ${{ matrix.c_compiler }} || echo "${{ matrix.c_compiler }} not found in PATH!"
+        which ${{ matrix.cpp_compiler }} || echo "${{ matrix.cpp_compiler }} not found in PATH!"
+
+        echo "Checking C++ compiler version:"
+        ${{ matrix.cpp_compiler }} --version || echo "Failed to get version for ${{ matrix.cpp_compiler }}"
+        echo "--------------------------------"
 
     - name: Set reusable strings
-      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
       id: strings
       shell: bash
       run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
+        echo "Using build directory: ${{ github.workspace }}/build"
 
     - name: Configure CMake
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
-      run: >
-        cmake -B ${{ steps.strings.outputs.build-output-dir }}
-        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
-        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
-        -S ${{ github.workspace }}
+      # Set environment variables for CMake to pick up the correct compilers
+      env:
+        CC: ${{ matrix.c_compiler }}
+        CXX: ${{ matrix.cpp_compiler }}
+      run: |
+        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
+              -S ${{ github.workspace }} \
+              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
+              -G Ninja # Specify Ninja generator
 
     - name: Build
-      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
-      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
+      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --verbose
 
     - name: Test
       working-directory: ${{ steps.strings.outputs.build-output-dir }}
-      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest --build-config ${{ matrix.build_type }}
+      # Execute tests defined by the CMake configuration.
+      # CTest defaults to Release config unless otherwise specified,
+      # but being explicit with --build-config doesn't hurt.
+      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure -V # Added -V for verbose test output
